
course: "CS8"
legacy_wiki_name: 8wiki
legacy_wiki_url: "https://foo.cs.ucsb.edu/8wiki" 
qtr: "M18"
quarter: "Summer 2018"
ta_list: "Sanjana, Tawny and Seemanta"
ta_list_full: "Sanjana Sahayaraj, Tawny Lim and Seemanta Saha"
instructor: "Nichols"

github_url: https://github.com/ucsb-cs8-m18/ucsb-cs8-m18.github.io
course_site: http://ucsb-cs8-m18.github.io

on_campus: http://proquest.safaribooksonline.com
off_campus: http://proquest.safaribooksonline.com.proxy.library.ucsb.edu:2048



legacy_wiki_url: https://foo.cs.ucsb.edu/8wiki
legacy_wiki_name: "8wiki"


start_week: 1
start_date: 2018-08-05 00:00:00.00-7:00
num_weeks: 6
extra_exam_week: false
sections: "11am,&nbsp;12:30pm,&nbsp;2pm&nbsp;or&nbsp;3:30pm"

cal_dates: >
  [
  {"label":"First day of session B", "date":"2018-08-06" },
  {"label":"Last day to Add","date":"2018-08-10" },
  {"label":"Last day to Add with code","date":"2018-08-16" },
  {"label":"Drop w/ Full Refund","date":"2018-08-10" },
  {"label":"Drop Deadline (no W grade)","date":"2018-08-21" },
  {"label":"Univ. Holiday", "date":"2018-09-03" },
  {"label":"Grade Option Change Deadline", "date":"2018-09-04" },    
  {"label":"Last day of session", "date":"2018-09-15" }			
  ]



kramdown:
   parse_block_html: true
   default_lang: python


exclude:
   - vendor
   - _exam/e02/cs56_m16_e02/code
   - _exam/e01/cs56_f16_e01/code


timezone: America/Los_Angeles

collections:
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  inclass:
    output: true
    permalink: /inclass/:path/
    last_before: false
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  labWIP:
    output: true
    permalink: /labWIP/:path/
    last_before: false
  exam:
    output: true
    permalink: /exam/:path/
  info:
    output: true
    permalink: /info/:path/
  teams:
    output: true
    permalink: /teams/:path/
  lectures:
    output: true
    permalink: /lectures/:path/



defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - 
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  - 
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  - 
    scope:
      path: ""
      type: labWIP
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  - 
    scope:
      path: ""
      type: teams
    values:
      layout: teams
  - 
    scope:
      path: ""
      type: info
    values:
      layout: info
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout
  - 
    scope:
      path: ""
      type: inclass
    values:
      layout: hwk


